model_project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shops.urls'))
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shops/urls.py
from django.urls import path
from .views import customer, shop, vespa,  object_predict, upload_image
urlpatterns = [
    path('', vespa, name='vespa'),
    path('shop/',  shop, name="shop"),
    path('customer/', customer, name="customer"),
    path('upload-image/', upload_image, name="upload_image"),
    path('predict/',  object_predict, name="predict")
]

shops/models.py
from django.db import models
import uuid
# Create your models here.
class Detection(models.Model):
    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name        = models.CharField(max_length=250)
    image       = models.ImageField(blank=True, null=True, upload_to='images/')

class Categorise(models.Model):
    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name        = models.CharField(max_length=250)
    cate       = models.CharField(max_length=250)

shops/forms.py
from django import forms
from .models import *
  
class DetectionForm(forms.ModelForm):
  
    class Meta:
        model = Detection
        fields = ['name', 'image']

shops/views.py
from django.http.response import JsonResponse
import matplotlib.pyplot as plt
from io import BytesIO
from django.shortcuts import render
import base64
from .dataset import allages, allprods, vesages, vesprods, pizages, pizprods
from collections import Counter
from scipy.stats import beta
import numpy as np
import matplotlib
matplotlib.use('Agg')
# Create your views here.
def shop(request):
    if request.method == "POST":
        p1l = int(request.POST.get('p1likes'))
        p1d = int(request.POST.get('p1dislikes'))
        p1o = int(request.POST.get('p1orders'))
        p2l = int(request.POST.get('p2likes'))
        p2d = int(request.POST.get('p2dislikes'))
        p2o = int(request.POST.get('p2orders'))
        p3l = int(request.POST.get('p3likes'))
        p3d = int(request.POST.get('p3dislikes'))
        p3o = int(request.POST.get('p3orders'))
        p4l = int(request.POST.get('p4likes'))
        p4d = int(request.POST.get('p4dislikes'))
        p4o = int(request.POST.get('p4orders'))
        def shop_recommend(shop):
            """Recommends what has to be Sold."""
            products = {
                    'MYSHOP': {'Product 1':[p1l,p1d,p1o], 'Product 2':[p2l,p2d,p2o],
                    'Product 3':[p3l,p3d,p3o], 'Product 4':[p4l,p4d,p4o]},
                    
                }
            def Beta(alpha, abeta):
                """ Finds the p-value of the product."""
                from scipy.stats import beta
                mean, var, skew, kurt = beta.stats(alpha, abeta, moments='mvsk')
                return mean

            def sortdict(dicname):
                """ Sorts a dictionary in Descending Order. """
                return dict(sorted(dicname.items(), key=lambda b: b[-1], reverse=True))

            data    = products[shop]
            pdict   = dict()
            orders  = dict()
            for key,val in data.items():
                pdict[key]  = Beta(val[0],val[1])
                orders[key] = val[2]

            recommend = dict()
            for prod in sortdict(pdict).keys():
                recommend[prod] = list(sortdict(orders).keys()).index(prod) + 1


            flag = dict()
            for pro,pos in recommend.items():
                if pos == 1:
                    """First 2 Leading to be bought and most preffered."""
                    flag[pro] = 0

            """ Among best four preffered. """
            for bb in sortdict(pdict).keys():
                    if bb not in flag.keys():
                        flag[bb] = 1
            return flag
        recoms = shop_recommend('MYSHOP')

        x = np.linspace(0, 1.0, 100)
        p1 = beta.pdf(x, p1l, p1d)
        p2 = beta.pdf(x, p2l, p2d)
        p3 = beta.pdf(x, p3l, p3d)
        p4 = beta.pdf(x, p4l, p4d)
        plt.plot(x, p1, "b-", x, p2, f"r-*", x, p3, "g*",x, p4,'m+')
        plt.xlabel('Probability', fontsize='15')
        plt.ylabel('Density', fontsize='15')
        buffer = BytesIO()
        plt.savefig(buffer, format='png')
        buffer.seek(0)
        image_png = buffer.getvalue()
        buffer.close()
        graphic = base64.b64encode(image_png)
        graphic = graphic.decode('utf-8')
        plt.close()
        
        context = {'graphic': graphic, 'results':True, 'data': recoms, 'title':'Shop Recommendation.'}
    else:
        context = {'title':'Shop Recommendation.'}
    
    template = 'shops.html'
    return render(request, template, context)


def customer(request):
    shops = ['Vespa Farms','Pizza Hut']
    if request.method == 'POST':
        age = int(request.POST.get('age'))
        shopie = request.POST.get('myshop')
        if str(shopie) == 'Pizza Hut':
            ages = pizages
            products = pizprods
        else:
            ages = vesages
            products = vesprods
        age15bel = []; age1620  = []; age2125  = []
        age2630  = []; age3135  = []; age3640  = []
        age4145  = []; age46abo = []
        for i in range(0, len(ages)):
            if ages[i] <= 15:
                age15bel.append(products[i])
            elif 16 <= ages[i] <= 20:
                age1620.append(products[i])
            elif 21 <= ages[i] <= 25:
                age2125.append(products[i])
            elif 26 <= ages[i] <= 30:
                age2630.append(products[i])
            elif 31 <= ages[i] <= 35:
                age3135.append(products[i])
            elif 36 <= ages[i] <= 40:
                age3640.append(products[i])
            elif 41 <= ages[i] <= 45:
                age4145.append(products[i])
            else:
                age46abo.append(products[i])
        
        if age <= 15:
            label = '0-15'
            group = age15bel
        elif 16 <= age <= 20:
            label = '16-20'
            group = age1620
        elif 21 <= age <= 25:
            label = '21-25'
            group  = age2125
        elif 26 <= age <= 30:
            label = '26-30'
            group = age2630
        elif 31 <= age <= 35:
            label = '31-35'
            group = age3135
        elif 36 <= age <= 40:
            label = '36-40'
            group = age3640
        elif 41 <= age <= 45:
            label = '41-45'
            group = age4145
        else:
            label = '46+'
            group = age46abo

        prodhists = dict(Counter(group))
        bidhaa    = list(prodhists.keys())
        orders    = list(prodhists.values())
        fig, ax   = plt.subplots()
        ax.bar(bidhaa, orders, 0.8, color='#17B897')
        ax.set_ylabel('Orders')
        ax.set_title(f'Products Vs Orders {label}')
        buffer = BytesIO()
        plt.savefig(buffer, format='png')
        buffer.seek(0)
        image_png = buffer.getvalue()
        buffer.close()
        graphic = base64.b64encode(image_png)
        graphic = graphic.decode('utf-8')
        plt.close()
        #plt.clf()


        """ Customer Recommendations."""
        context = {'shops': shops, 'results': True,'graphic': graphic}
    else:
        context = {'shops': shops, 'results': False}
    template = 'customers.html'
    return render(request, template, context)

def vespa(request):
    template = 'vespa.html'
    context = {'Shopps': 'Vespas', 'choices' :['Shops','Customers']}
    return render(request, template, context)



import keras
from keras.preprocessing import image
from keras.applications import imagenet_utils
import tensorflow
import os.path
from model_project.settings import  MEDIA_ROOT
img_path = MEDIA_ROOT + '\\images\\'
from django.conf import settings
from .models import Detection, Categorise
def object_predict(request):
    detects = Detection.objects.all()
    if request.method == 'POST':
        imname = str(request.POST.get('mydet'))
        imageurl = str(Detection.objects.filter(name=imname).first().image.url)[13:]
        mobile = tensorflow.keras.applications.mobilenet.MobileNet()
        def prepare_image(file):
            img_path = MEDIA_ROOT + '\\images\\'
            img = image.load_img(img_path + file, target_size=(224, 224))
            img_array = image.img_to_array(img)
            img_array_expanded_dims = np.expand_dims(img_array, axis=0)
            return keras.applications.mobilenet.preprocess_input(img_array_expanded_dims)
    
        preprocessed_image = prepare_image(f'{imageurl}')
        predictions = mobile.predict(preprocessed_image)
        results = imagenet_utils.decode_predictions(predictions)

        def modify(line):
            import re
            line = re.sub('[_]', ' ', line)
            return line.title()
        analysis = {}
        for i in range(0, len(results[0])):
            analysis[modify(results[0][i][1])] = results[0][i][2]
        confidence = str(int(round(float(list(analysis.values())[0]), 2)*100))
        detected = list(analysis.keys())[0]

        if Categorise.objects.filter(name=detected).exists():
            flag =  'Reject'
        else:
            flag = 'Allow'
        context = {'data': analysis, 'detects':detects, 'results':True ,'detected':detected, 'confidence': confidence}
    else:
        context = {'detects':detects, 'results': False}
    template = 'predict.html'
    return render(request, template, context)


from django.shortcuts import render, redirect
from .forms import *
def upload_image(request):
    if request.method == 'POST':
        form = DetectionForm(request.POST, request.FILES)
        
        if form.is_valid():
            form.save()
            return redirect('predict')
    else:
        form = DetectionForm()
    return render(request, 'input.html', {'form' : form})

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% if title %}
        <title>Vespa Models - {{ title }}</title>
    {% else %}
        <title>Vespa Models</title>
    {% endif %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <style>
        #displayed {
        display: block;
        margin-left: auto;
        margin-right: auto
    }
    
    </style>
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-md bg-dark navbar-dark">
            <a class="navbar-brand" href="{% url 'vespa' %}"><span class="display-5 font-weight-bold">dLab Vespas</span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav text-light">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop' %}">Shop</a>
                </li>
                <li class="nav-item">
                <a class="nav-link" href="{% url 'customer' %}">Customer</a>
                </li>  
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'upload_image' %}">Upload</a>
                </li>  
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'predict' %}">PIFD</a>
                </li> 
                <li class="nav-item">
                    <a class="nav-link" target="blank" href="http://127.0.0.1:8001">Store</a>
                </li> 
            </ul>
            </div>  
        </nav>
    </div>
    <div class="container">
        {% block content %}{% endblock content %}
    </div>
</body>

templates/customers.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-lg-6">
            <h3 class="text text-center display-4">Customer (Age&Shop) Viz</h3>
            <hr class="pb-2">
            <form class="form-group" action="{% url 'customer' %}" method="POST">{% csrf_token %}
                <div class="container pb-4">

                    <div class="form-row">
                            <div class="col">
                            </div>
                            <div class="col">
                                <h5 class="text text-dark">Age</h5>
                                <input style="width: 120px; height: 25px;" type="number" class="form-control" name="age" required>
                            </div>
                            <div class="col">
                                <h5 class="text text-dark">Shop</h5>
                                <select class="form-control" style="width: 120px; height: 25px;" id="myshop" name="myshop" required>
                                    {% for shop in shops %}
                                    <option required>{{ shop }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="col">
                        </div>
                    </div>
                </div>
                <div class="container  text-center">
                    <button class="btn btn-primary" type="submit">Visualize</button>
                </div>
            </form>
        </div>
        {% if results %}
        <div id="displayed" class="col-lg-6 justify-content-center">
            <h4 class="text text-primary text-center font-weight-bold">AGE GROUP GRAPH</h4>
            <img style="height: 300px; width: 450px; margin-top: -7px;" src="data:image/png;base64,{{ graphic|safe }}">
        </div>
    {% else %}
        <div id="isplayed" class="col-lg-6 justify-content-center">
            <p class="text text-center text-info display-4">Fill & Hit <strong>RECOMMEND</strong></p>
        </div>
    {% endif %}
    </div>
</div>
{% endblock content %}

templates/input.html
{% extends 'base.html' %}
{% block content %}
<style>
@import url(https://fonts.googleapis.com/css?family=Open+Sans:700,300);

.frame {
	position: absolute;
	top: 50%;
	left: 50%;
	width: 400px;
	height: 400px;
	margin-top: -200px;
	margin-left: -200px;
	border-radius: 2px;
	box-shadow: 4px 8px 16px 0 rgba(0, 0, 0, 0.1);
	overflow: hidden;
	background: linear-gradient(to top right, darkmagenta 0%, hotpink 100%);
	color: #333;
	font-family: "Open Sans", Helvetica, sans-serif;
}

.center {
	position: absolute;
	top: 50%;
	left: 50%;
	transform: translate(-50%, -50%);
	width: 300px;
	height: 260px;
	border-radius: 3px;
	box-shadow: 8px 10px 15px 0 rgba(0, 0, 0, 0.2);
	background: #fff;
	display: flex;
	align-items: center;
	justify-content: space-evenly;
	flex-direction: column;
}

.title {
	width: 100%;
	height: 50px;
	border-bottom: 1px solid #999;
	text-align: center;
}

h1 {
	font-size: 16px;
	font-weight: 300;
	color: #666;
}

.dropzone {
	width: 100px;
	height: 80px;
	border: 1px dashed #999;
	border-radius: 3px;
	text-align: center;
}

.upload-icon {
	margin: 25px 2px 2px 2px;
}

#id_image {
	position: relative;
	top: -62px;
	left: 0;
	width: 100%;
	height: 100%;
	opacity: 0;
}

#id_name {
	border: 2px solid darkolivegreen;
}
.btn {
	display: block;
	width: 140px;
	height: 40px;
	background: dodgerblue;
	color: #fff;
	border-radius: 3px;
	border: 0;
	transition: all 0.3s ease-in-out;
	font-size: 14px;
}

.btn:hover {
	background: rgb(51, 129, 153);
	box-shadow: 0 3px 0 0 rgb(139, 228, 240);
}
</style>

<div class="frame">
	<form method="POST" id="myform" action="{% url 'upload_image' %}" enctype="multipart/form-data">{% csrf_token %}
		<div class="container pb-2">
			<div class="form-row">
				<div class="center">
					<div class="title">
						<p class="font-weight-bold" style="margin-top: -10px;">Name of Label</p>
						{{ form.name }}
					</div>
		
					<div class="dropzone">
						<img src="http://100dayscss.com/codepen/upload.svg" class="upload-icon" />
						{{ form.image }}
					</div>
					<button type="button" onclick="submitForm()" class="btn" name="uploadbutton">Upload file</button>
				</div>
			</div>
		</div>
	</form>
</div>

<!-- original pen: https://codepen.io/roydigerhund/pen/ZQdbeN  -->

<!-- NO JS ADDED YET -->
</div>
<script>
	function submitForm(){
		kalo = document.getElementById("myform");
		var kalo;
		kalo.submit();
	}
</script>

{% endblock content %}

templates/predict.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-lg-6">
            <h3 class="text text-center display-5 font-weight-bold">Product Image Fraud Detection</h3>
            <hr class="pb-3">
            <form class="form-group" id="myForm" action="{% url 'predict' %}" method="POST">{% csrf_token %}
                <div class="container pb-4">
                    <div class="form-row">
                        <div class="col">
                        </div>
                        <div class="col">
                            <h5 class="text" style="color: blue;">Select Your Image Label</h5>
                            <select class="form-control" style="width: 200px; height: 30px;" id="mydet" name="mydet" required>
                                {% for det in detects %}
                                <option required>{{ det.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                        <div class="col">
                        </div>
                    </div>
                </div>

                <div class="container pb-1">
                    <button class="btn btn-primary btn-block" onclick="submitForm()">DETECT</button>
                </div>
                        
                {% if results %}
                    <div class="container " style="background-color: aliceblue;">
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-success btn-block" data-toggle="modal" data-target="#exampleModalLong">
                            Findings
                        </button>
                        <!-- Modal -->
                        <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                <h5 class="text text-center font-weight-bold">Analysis Results</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                </div>
                                <div class="modal-body">
                                    <table class="table">
                                        <thead class="thead-dark">
                                            <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">RELATED</th>
                                            <th scope="col">PROBABILITY</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for key, val in data.items %}
                                            <tr>
                                            <th scope="row">{{ forloop.counter }}</th>
                                            <td>{{ key }}</td>
                                            <td>{{ val }}</td>
                                            </tr>
                                            {% endfor%}
                                        </tbody>
                                    </table>
                                </div>
                                <div class="modal-footer">
                                <button type="button" class="btn btn-danger" data-dismiss="modal">CLOSE</button>
                                </div>
                            </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </form>
        </div>
        {% if results %}
        <div id="isplayed" class="col-lg-6 justify-content-center">
            <p class="text-center text-info font-weight-bold">RESULTS</p> 
            <p class="display-4 text-center font-weight-bold">{{ detected|title }} ({{ confidence }}%)</p>
        <div>
        {% else %}
            <div id="isplayed" class="col-lg-6 justify-content-center">
                <p class="display-4 p-3">Your Results will appear here .....</p>
            </div>
        {% endif %}
    </div>
</div>
<script>
	function submitForm(){
		kalo = document.getElementById("myForm");
		var kalo;
		kalo.submit();
	}
</script>

{% endblock content %}

templates/shops.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-lg-6">
            <h3 class="text text-center display-3 font-weight-bold">Shops</h3>
            <hr>
            <form class="form-group" id="myForm" action="{% url 'shop' %}" method="POST">{% csrf_token %}
                <div class="container pb-2">
                    <div>
                        <h5 class="text text-center" style="color: blue;">Product 1</h5>
                    </div>
                    <div class="form-row">
                            <div class="col">
                                <input type="number" class="form-control" placeholder="Likes" name="p1likes" required>
                            </div>
                            <div class="col">
                                <input type="number" class="form-control" placeholder="Dislikes" name="p1dislikes" required>
                            </div>
                            <div class="col">
                                <input type="number" class="form-control" placeholder="Orders" name="p1orders" required>
                            </div>
                    </div>
                </div>
                <div class="container pb-2">
                    <div>
                        <h5 class="text text-center" style="color: red;">Product 2</h5>
                    </div>
                    <div class="form-row">
                            <div class="col">
                                <input type="number" class="form-control" placeholder="Likes" value=26 name="p2likes" required>
                            </div>
                            <div class="col">
                                <input type="number" class="form-control" placeholder="Dislikes" value=7 name="p2dislikes" required>
                            </div>
                            <div class="col">
                                <input type="number" class="form-control" placeholder="Orders"  value=10 name="p2orders" required>
                            </div>
                    </div>
                </div>
                <div class="container pb-2">
                    <div>
                        <h5 class="text text-center" style="color: green;">Product 3</h5>
                    </div>
                    <div class="form-row">
                            <div class="col">
                                <input type="number" class="form-control" placeholder="Likes" value=16 name="p3likes" required>
                            </div>
                            <div class="col">
                                <input type="number" class="form-control" placeholder="Dislikes" value=2 name="p3dislikes" required>
                            </div>
                            <div class="col">
                                <input type="number" class="form-control" placeholder="Orders" value=26 name="p3orders" required>
                            </div>
                    </div>
                </div>
                <div class="container pb-4">
                    <div>
                        <h5 class="text text-center" style="color: magenta;">Product 4</h5>
                    </div>
                    <div class="form-row">
                            <div class="col">
                                <input type="number" class="form-control" placeholder="Likes" value=16 name="p4likes" required>
                            </div>
                            <div class="col">
                                <input type="number" class="form-control" placeholder="Dislikes" value=4 name="p4dislikes" required>
                            </div>
                            <div class="col">
                                <input type="number" class="form-control" placeholder="Orders" value=56 name="p4orders" required>
                            </div>
                    </div>
                </div>
                <div class="container pb-1">
                    <button class="btn btn-primary btn-block" type="submit">RECOMMEND</button>
                </div>
                        
                {% if results %}
                    <div class="container " style="background-color: aliceblue;">
                        <!-- Button trigger modal -->
                        <button type="button" class="btn btn-success btn-block" data-toggle="modal" data-target="#exampleModalLong">
                            See Results
                        </button>
                        
                        <!-- Modal -->
                        <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
                            <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                <h5 class="text text-center font-weight-bold">Shop Recommendations</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                                </div>
                                <div class="modal-body">
                                      <table class="table">
                                        <thead class="thead-dark">
                                          <tr>
                                            <th scope="col">#</th>
                                            <th scope="col">PRODUCT</th>
                                            <th scope="col">RECOMMEND</th>
                                          </tr>
                                        </thead>
                                        <tbody>
                                            {% for key, val in data.items %}
                                          <tr>
                                            <th scope="row">{{ forloop.counter }}</th>
                                            <td>{{ key }}</td>
                                            <td>{{ val }}</td>
                                          </tr>
                                          {% endfor%}
                                        </tbody>
                                      </table>
                                </div>
                                <div class="modal-footer">
                                <button type="button" class="btn btn-danger" data-dismiss="modal">CLOSE</button>
                                </div>
                            </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </form>
        </div>
        {% if results %}
            <div id="displayed" class="col-lg-6 justify-content-center">
                <h4 class="text text-primary text-center font-weight-bold">BETA DISTRIBUTION</h4>
                <img style="height: 300px; width: 450px; margin-top: -7px;" src="data:image/png;base64,{{ graphic|safe }}">
            </div>
        {% else %}
            <div id="isplayed" class="col-lg-6 justify-content-center">
                <p class="text text-center text-info display-4">Fill & Hit <strong>RECOMMEND</strong></p>
            </div>
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/vespa.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-4" >
    <p class="display-3 font-weight-bold text-center p-4">Team Vespa Model</p>
    <div class="row">
        <div class="col-2">

        </div>
        <div class="col">
            <a style="height: 30px;" href="{% url 'shop' %}" class="form-control btn btn-outline-info">Shops</a>
        </div>
        <div class="col">
            <a style="height: 30px;" href="{% url 'customer' %}" class="form-control btn btn-outline-info">Customers</a>
        </div>
        <div class="col-2">

        </div>
    </div>

    <div class="row justify-content-center p-4">
            <div>
                <ul  class="d-flex mt-2" style="list-style-type:circle; padding-left: -20px;">
                    <li  style="padding-right: 20px;">Ashura</li>
                    <li style="padding-right: 20px;">Elizabeth</li>
                    <li style="padding-right: 20px;">Dorothy</li>
                    <li style="padding-right: 20px;">Kalokola</li>
                </ul>
            </div>        
    </div>
    <div class="row justify-content-center">
        <p class="text text-muted" style="font-family:cursive;">Thanks to: <strong class="display-7">The dLab Staff</strong>, Madam Somoe, Ally, Megan, Kevin and Our Fellow PT Students</p>
    </div>
</div>
<div>
    
</div>
{% endblock content %}